Vagrant.configure("2") do |config|
    config.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "8192"
      v.vmx["numvcpus"] = "4"
      v.gui = true
    end

    config.vm.define "Jenkins_VM" do |n|
      n.vm.box = "almalinux/9"
      n.vm.base_mac = "00:0c:29:c1:b1:5a"
      n.vm.base_address = "192.168.157.77"
      n.vm.provision "shell", inline: <<-SHELL
      echo 'root:almalinux' | chpasswd
      useradd -m -s /bin/bash jenkins
      echo 'jenkins:jenkins' | chpasswd
      usermod -aG wheel jenkins
      mkdir -p /home/jenkins/.ssh
      chmod 700 /home/jenkins/.ssh
      chown -R jenkins:jenkins /home/jenkins/.ssh

      hostnamectl set-hostname jenkins
    SHELL
    end
  end
